---
# tasks file for common
- name: "update cache"
  package:
    update_cache: yes
  become: yes

- name: "install basic packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ package }}"

- name: "copy fail2ban conf"
  copy:
    src: "{{ role_path }}"/files/ssh.conf
    dest: /etc/fail2ban/jail.d
